---
# tasks file for mfic.docker-nextcloud
- name: Make sure base path exists
  ansible.builtin.file:
    path: "{{ site_working_directory }}"
    state: directory

- name: Make sure config directory exists
  ansible.builtin.file:
    path: "{{ site_working_directory }}/conf.d"
    state: directory

- name: Copy required files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ site_working_directory }}"
  with_items:
    - docker-compose.yml

- name: Copy php.ini
  ansible.builtin.template:
    src: "conf.d/php.ini"
    dest: "{{ site_working_directory }}/conf.d/php.ini"

- name: Get Traefik container IP from webproxy network
  shell: docker inspect -f '{{"{{"}} .NetworkSettings.Networks.webproxy.IPAddress {{"}}"}}' traefik-traefik-1
  register: traefik_container_ip
  tags:
    - update_traefik_ip

- name: Show Traefik container IP
  debug:
    msg: "Traefik container IP is {{ traefik_container_ip.stdout }}"
  tags:
    - update_traefik_ip

- name: Ensure trusted_proxies and forwarded_for_headers exist in Nextcloud config.php
  blockinfile:
    path: "{{ site_working_directory }}/{{ nc_volume_config }}/config.php"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Trusted Proxies and Forwarded Headers"
    content: |
      'trusted_proxies' => ['{{ traefik_container_ip.stdout }}', '{{ host_ip }}'],
      'forwarded_for_headers' => ['HTTP_X_FORWARDED_FOR', 'HTTP_X_REAL_IP'],
    insertbefore: "^\\);$"
  tags:
    - update_traefik_ip

- name: Set default phone region in Nextcloud config.php
  lineinfile:
    path: "{{ site_working_directory }}/{{ nc_volume_config }}/config.php"
    regexp: "'default_phone_region' =>"
    line: "'default_phone_region' => '{{ nc_phone_region_iso_code }}',"
    insertafter: "'maintenance' =>"
  notify:
    - Restart Nextcloud
